// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'Admin/Posts/Edit' | 'Admin/Posts/Index' | 'Admin/Posts/New' | 'Errors/InternalServerError' | 'Errors/NotFound' | 'Posts/Index' | 'Posts/Show'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Admin/Posts/Edit': unknown
    'Admin/Posts/Index': unknown
    'Admin/Posts/New': unknown
    'Errors/InternalServerError': unknown
    'Errors/NotFound': unknown
    'Posts/Index': unknown
    'Posts/Show': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
